version: "3.7"
services:

  # battleships-db
  battleships-db:
    image: postgres
    container_name: battleships-db
    ports:
      - 5532:5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=battleships
      - POSTGRES_PASSWORD=battleships
      - POSTGRES_DB=battleships
    restart: always